process.env.INTEGRATION = 'mock';
process.env.APPROVAL_TENS_INTENSITY_LIMIT_DISABLED = 'false';
process.env.APPROVAL_TENS_PARTS_LIMIT_DISABLED = 'false';
process.env.ANORMALY_ULTRASOUND_ZERO_TEMPERATURE_DURATION_SECONDS_DISABLED = 'false';
process.env.ANORMALY_ULTRASOUND_OVERTHEAT_DURATION_SECONDS_DISABLED = 'false';
