---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: acme-controller-job
  name: acme-controller-wsservice
  namespace: ankh
spec:
  selector:
    app: acme-controller-job
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
