// This file is auto-generated by @hey-api/openapi-ts

export type JobStatus = 'pendingapproval' | 'pending' | 'standby' | 'play' | 'frozen' | 'complete' | 'cancelled' | 'abnormal';

export type BaseUser = {
    userNumber: string;
    name: string;
    locationId: string;
};

export type User = BaseUser & {
    userId: string;
    createdAt: string;
    job: Array<{
        jobId: string;
    }>;
};

export type BaseAssignee = {
    username: string;
    locationId: string;
    role: 'device_admin' | 'device_user' | 'device_maintenance';
};

export type AssigneeRequest = BaseAssignee & {
    password: string;
};

export type Assignee = BaseAssignee & {
    assigneeId: string;
};

export type BaseLocation = {
    name: string;
    group: string;
};

export type Location = BaseLocation & {
    locationId: string;
    device: Array<{
        deviceId?: string;
    }>;
};

export type ChannelLimit = {
    /**
     * TENS_CH1_Intensity_Limit
     */
    ch1: number;
    /**
     * TENS_CH2_Intensity_Limit
     */
    ch2: number;
    /**
     * TENS_CH3_Intensity_Limit
     */
    ch3: number;
    /**
     * TENS_CH4_Intensity_Limit
     */
    ch4: number;
};

export type Channel = {
    /**
     * Actual_TENS_CH1_Intensity
     */
    ch1: number;
    /**
     * Actual_TENS_CH2_Intensity
     */
    ch2: number;
    /**
     * Actual_TENS_CH3_Intensity
     */
    ch3: number;
    /**
     * Actual_TENS_CH4_Intensity
     */
    ch4: number;
};

export type BiChannelLimit = {
    /**
     * TENS_CH1_Heat_Limit: 0:L/1:M/2:H
     */
    ch1: 0 | 1 | 2;
    /**
     * TENS_CH2_Heat_Limit: 0:L/1:M/2:H
     */
    ch2: 0 | 1 | 2;
};

export type BiChannel = {
    /**
     * Actual_TENS_CH1_Temperature: 0=1/1=M/2=H
     */
    ch1: 0 | 1 | 2;
    /**
     * Actual_TENS_CH2_Temperature: 0=1/1=M/2=H
     */
    ch2: 0 | 1 | 2;
};

export type SnapshotTime = {
    startedAt: string;
    timeRemain: {
        value: number;
        unit: 'minute' | 'second';
    };
};

export type Acknowledgement = {
    type: 'acknowledgement';
    detail: {
        commandId: Array<string>;
        version?: string;
    };
};

export type UltrasoundSetting = {
    /**
     * Ultrasound_Scheme_Enable
     */
    scheme: {
        oneMContinuous: boolean;
        threeMContinuous: boolean;
        oneMPulse: boolean;
        threeMPulse: boolean;
    };
    intensityLimit: {
        /**
         * Ultrasound_Intensity_Limit_1M_C
         */
        oneMC: number;
        /**
         * Ultrasound_Intensity_Limit_3M_C
         */
        threeMC: number;
        /**
         * Ultrasound_Intensity_Limit_1M_P
         */
        oneMP: number;
        /**
         * Ultrasound_Intensity_Limit_3M_P
         */
        threeMP: number;
    };
    /**
     * Ultrasound_Pulse_Frequency: 0=10Hz/1=20Hz/2=50Hz/3=100Hz
     */
    pulseFrequencyInHz: {
        oneM: 0 | 1 | 2 | 3;
        threeM: 0 | 1 | 2 | 3;
    };
    /**
     * Ultrasound_Pulse_Duty_Ratio: 0=1:1/1=1:2/2=1:5/3=1:10
     */
    pulseDutyRatio: {
        oneM: 0 | 1 | 2 | 3;
        threeM: 0 | 1 | 2 | 3;
    };
    /**
     * Ultrasound_Temperature_Threshold
     */
    temperatureThreshold: 0 | 1 | 2;
};

export type TensSetting = {
    /**
     * TENS_Waveform_Enable
     */
    waveform: {
        wf1: boolean;
        wf2: boolean;
        wf3: boolean;
        wf4: boolean;
        wf5: boolean;
        wf6: boolean;
    };
    /**
     * TENS_Channel_Enable
     */
    channel: {
        ch1: boolean;
        ch2: boolean;
        ch3: boolean;
        ch4: boolean;
    };
    intensitylimit: ChannelLimit;
    heatLimit: BiChannelLimit;
};

export type ProNewTreatmentPlan = {
    type: 'pronew';
    plan: {
        ultrasound: number;
        tens: number;
    };
};

export type TreatmentPlanUpdate = ProNewTreatmentPlan;

export type TreatmentPlanHistory = TreatmentPlanUpdate & {
    author: string;
    updatedAt: string;
};

export type ProNewTreatmentPlanWithVersion = ProNewTreatmentPlan & {
    version: string;
};

export type TreatmentPlanCreateRequest = {
    type: 'pronew';
};

export type TreatmentPlanWithVersionAndName = ProNewTreatmentPlanWithVersion & {
    treatmentPlanId: string;
    name: string;
    group: string;
    updatedAt: string;
};

export type TreatmentPlanWithVersionAndNameAndHistory = TreatmentPlanWithVersionAndName & {
    history: Array<TreatmentPlanHistory>;
};

export type CustomizableProNewTreatmentPlanWithVersion = ProNewTreatmentPlanWithVersion & {
    customizable: boolean;
    enabled: boolean;
};

export type ProNewTreatmentPlanToggle = {
    customizable: boolean;
    enabled: boolean;
};

/**
 * Treatment_Plan_Enable
 */
export type ProNewTreatmentPlanSetting = {
    preset: {
        pronew001: ProNewTreatmentPlanToggle;
        pronew002: ProNewTreatmentPlanToggle;
        pronew003: ProNewTreatmentPlanToggle;
        pronew004: ProNewTreatmentPlanToggle;
        pronew005: ProNewTreatmentPlanToggle;
        pronew006: ProNewTreatmentPlanToggle;
        pronew007: ProNewTreatmentPlanToggle;
        pronew008: ProNewTreatmentPlanToggle;
    };
};

/**
 * Treatment_Plan_Enable
 */
export type ProNewPlanSetting = {
    preset: {
        pronew001: CustomizableProNewTreatmentPlanWithVersion;
        pronew002: CustomizableProNewTreatmentPlanWithVersion;
        pronew003: CustomizableProNewTreatmentPlanWithVersion;
        pronew004: CustomizableProNewTreatmentPlanWithVersion;
        pronew005: CustomizableProNewTreatmentPlanWithVersion;
        pronew006: CustomizableProNewTreatmentPlanWithVersion;
        pronew007: CustomizableProNewTreatmentPlanWithVersion;
        pronew008: CustomizableProNewTreatmentPlanWithVersion;
    };
};

/**
 * Treatment_Plan_Enable
 */
export type ProPlanSetting = {
    ultrasound30Tens0: boolean;
    ultrasound20Tens10: boolean;
    ultrasound10Tens20: boolean;
    ultrasound0Tens30: boolean;
};

export type ProSetting = {
    plan: ProNewTreatmentPlanSetting | ProNewPlanSetting | ProPlanSetting;
    ultrasoundSetting: UltrasoundSetting;
    tensSetting: TensSetting;
};

export type BaseJob = {
    treatmentPlan: {
        type: 'pro' | 'pronew';
        detail: ProSetting;
    };
};

export type BaseJobWithAssignee = BaseJob & {
    assigneeId: string;
    userId: string;
};

export type BaseJobWithAssigneeWithDeviceId = BaseJobWithAssignee & {
    deviceId: string;
};

export type BaseJobWithJobId = BaseJob & {
    jobId: string;
};

export type JobUpdateStatus = {
    status: 'play' | 'frozen' | 'cancelled';
};

export type BaseJobWithJobIdAndAssigneeAndStatus = BaseJobWithJobId & {
    userId: string;
    assigneeId: string;
    status: JobStatus;
};

export type BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId = BaseJobWithJobIdAndAssigneeAndStatus & {
    datetime?: string;
    deviceId: string;
    offlineJobId?: string;
};

export type TreatmentWithJobIdAndStatusAndAssigneeAndDeviceId = {
    detail: {
        treatment: TreatmentSnapshot;
    };
    userId: string;
    deviceId: string;
    assigneeId: string;
    status: JobStatus;
    jobId: string;
};

export type TreatmentPlanWithJobIdAndStatusAndAssigneeAndDeviceId = {
    detail: BaseJob;
    deviceId: string;
    userId: string;
    assigneeId: string;
    status: JobStatus;
    jobId: string;
};

export type ErrorWithJobIdAndStatusAndAssigneeAndDeviceId = {
    detail: DeviceError;
    deviceId: string;
    userId: string;
    assigneeId: string;
    status: JobStatus;
    jobId: string;
};

export type BaseJobWithJobIdAndStatusAndAssigneeAndDeviceIdAndHistory = BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId & {
    jobHistory: Array<(TreatmentPlanWithJobIdAndStatusAndAssigneeAndDeviceId | TreatmentWithJobIdAndStatusAndAssigneeAndDeviceId | ErrorWithJobIdAndStatusAndAssigneeAndDeviceId) & {
        jobHistoryId: string;
        author: string;
        type: string;
        datetime?: string;
    }>;
};

export type AssigneeAtJob = {
    username: string;
    hash: string;
};

export type JobDetail = BaseJobWithJobId & {
    action: 'create' | 'update';
    assignee: AssigneeAtJob;
};

export type JobAction = {
    action: 'freeze' | 'play' | 'cancel';
    jobId: string;
};

export type Ping = {
    command: 'ping';
};

export type BaseMasterProgram = {
    version: string;
};

export type BaseMasterProgramWithDetail = {
    version: string;
    datetime: string;
};

export type MasterProgramUpgradeDetail = {
    VersionCode: string;
    VersionName: string;
    ModifyContent: string;
    DownloadUrl: string;
    ApkSize: string;
    ApkMd5: string;
};

export type MasterProgramUpgrade = {
    command: 'masterprogramupgrade';
    detail: MasterProgramUpgradeDetail;
};

export type BaseCommand = {
    command: JobDetail | JobAction | Ping | MasterProgramUpgrade;
};

export type Command = BaseCommand & {
    id: string;
    createDate: string;
    type: 1 | 2 | 3 | 4;
};

export type CommandWithStatus = Command & {
    status: 'pending' | 'pending-processing' | 'acknowledged';
};

export type UltrasoundSnapshot = {
    /**
     * Ultrasound_Scheme_Selected
     */
    scheme: 'oneMContinuous' | 'threeMContinuous' | 'oneMPulse' | 'threeMPulse';
    /**
     * Actual_Ultrasound_Intensity
     */
    intensity: number;
    /**
     * Actual_Ultrasound_Pulse_Frequency: 0=10Hz/1=20Hz/2=50Hz/3=100Hz
     */
    pulseFrequencyInHz: 0 | 1 | 2 | 3;
    /**
     * Actual_Ultrasound_Pulse_Duty_Ratio: 0=1:1/1=1:2/2=1:5/3=1:10
     */
    pulseDutyRatio: 0 | 1 | 2 | 3;
    /**
     * Actual_Ultrasound_Temperature: 数据范围 = 0-119; 0=-20°C; 119=99°C
     */
    temperature: number;
    time?: SnapshotTime;
};

export type TensSnapshot = {
    /**
     * Actual_TENS_Waveform
     */
    waveform: 'wf1' | 'wf2' | 'wf3' | 'wf4' | 'wf5' | 'wf6';
    intensity: Channel;
    temperature: BiChannel;
    time?: SnapshotTime;
};

/**
 * Treatment_Plan_Selected
 */
export type ProNewPlanSnapshot = {
    plan: {
        tens: number;
        ultrasound: number;
    };
    name: 'pronew001' | 'pronew002' | 'pronew003' | 'pronew004' | 'pronew005' | 'pronew006' | 'pronew007' | 'pronew008';
};

/**
 * Treatment_Plan_Selected
 */
export type ProPlanSnapshot = 'ultrasound30Tens0' | 'ultrasound20Tens10' | 'ultrasound10Tens20' | 'ultrasound0Tens30' | 'ultrasoundXTensY';

export type ProSnapshot = {
    plan: ProNewPlanSnapshot | ProPlanSnapshot;
    ultrasoundSnapshot: UltrasoundSnapshot;
    tensSnapshot: TensSnapshot;
};

export type TreatmentSnapshot = {
    type: 'pro' | 'pronew';
    detail: ProSnapshot;
};

export type JobHistory = {
    type: 'interim' | 'completion';
    jobId: string;
    offlineJobId?: string;
    detail: {
        assigneeUsername: string;
        status: 'pendingapproval' | 'standby' | 'Standby' | 'play' | 'Play' | 'pause' | 'Pause' | 'frozen' | 'Frozen' | 'complete' | 'Complete' | 'cancelled' | 'Cancel' | 'cancel' | 'abnormal' | 'Abnormal';
        treatment: TreatmentSnapshot;
    };
};

export type DeviceError = {
    error: 'ultrasoundOverheat' | 'tensCh1Shorted' | 'tensCh2Shorted' | 'tensCh3Shorted' | 'tensCh4Shorted';
    startedAt: string;
    endedAt?: string;
};

export type ErrorHistory = {
    detail: DeviceError;
    type: 'error';
    jobId: string;
    offlineJobId?: string;
};

export type DeviceReport = {
    detail: Array<JobHistory | ErrorHistory>;
};

export type BaseDevice = {
    code: string;
    type: string;
    locationId: string;
};

export type DeviceStatus = {
    status: 'online' | 'offline' | 'unknown';
    passwordUpdated?: boolean;
    masterProgramVersion?: string;
};

export type DeviceHistory = {
    datetime: string;
    detail: DeviceStatus;
};

export type Device = BaseDevice & {
    deviceId: string;
    passcode?: string;
    status: string;
    masterProgramVersion?: string;
    deviceHistory: Array<DeviceHistory>;
};

export type DeviceRequest = BaseDevice & {
    password: string;
};

export type EventReport = JobHistory | ErrorHistory | Acknowledgement;

export type Event = {
    eventId: string;
    datetime: string;
    type: 'heartbeat' | 'devicereport' | 'healthcheck' | 'ping';
    detail: {
        deviceId: string;
        report: DeviceReport;
    } | {
        [key: string]: unknown;
    };
    status: string;
    deviceId?: string;
};

export type AuthenticationRequest = {
    username: string;
    password: string;
    type: 'device' | 'user';
};

export type _Error = {
    error_code: string;
    error_message: string;
};

export type ConnectivityBase = {
    code: number;
    message: string;
};

export type ConnectivityError = ConnectivityBase & {
    object: {
        [key: string]: unknown;
    } | null;
};

export type UserIdPath = string;

export type LocationIdPath = string;

export type AssigneeIdPath = string;

export type DeviceIdPath = string;

export type JobIdPath = string;

export type GroupPath = string;

export type TreatmentPlanIdPath = string;

export type JobId = string;

export type DeviceId = string;

export type CommandId = string;

/**
 * Command status
 */
export type CommandStatus = Array<'pending' | 'pending-processing' | 'acknowledged'>;

/**
 * Include deleted
 */
export type IncludeDeleted = boolean;

/**
 * Force command
 */
export type ForceCommand = boolean;

export type GetCommandsWithKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/command';
};

export type GetCommandsWithKeyErrors = {
    400: ConnectivityError;
    401: ConnectivityError;
    403: ConnectivityError;
    404: ConnectivityError;
    500: ConnectivityError;
};

export type GetCommandsWithKeyError = GetCommandsWithKeyErrors[keyof GetCommandsWithKeyErrors];

export type GetCommandsWithKeyResponses = {
    200: ConnectivityBase & {
        object: {
            command: Array<Command>;
        };
    };
};

export type GetCommandsWithKeyResponse = GetCommandsWithKeyResponses[keyof GetCommandsWithKeyResponses];

export type AcknowledgeCommandWithKeyData = {
    body?: Acknowledgement;
    path?: never;
    query?: never;
    url: '/v1.0/acknowledgement';
};

export type AcknowledgeCommandWithKeyErrors = {
    400: ConnectivityError;
    401: ConnectivityError;
    403: ConnectivityError;
    404: ConnectivityError;
    500: ConnectivityError;
};

export type AcknowledgeCommandWithKeyError = AcknowledgeCommandWithKeyErrors[keyof AcknowledgeCommandWithKeyErrors];

export type AcknowledgeCommandWithKeyResponses = {
    200: ConnectivityBase & {
        object: Acknowledgement;
    };
};

export type AcknowledgeCommandWithKeyResponse = AcknowledgeCommandWithKeyResponses[keyof AcknowledgeCommandWithKeyResponses];

export type CreateDeviceReportWithKeyData = {
    body?: DeviceReport;
    path?: never;
    query?: never;
    url: '/v1.0/report';
};

export type CreateDeviceReportWithKeyErrors = {
    400: ConnectivityError;
    401: ConnectivityError;
    403: ConnectivityError;
    404: ConnectivityError;
    500: ConnectivityError;
};

export type CreateDeviceReportWithKeyError = CreateDeviceReportWithKeyErrors[keyof CreateDeviceReportWithKeyErrors];

export type CreateDeviceReportWithKeyResponses = {
    201: ConnectivityBase & {
        object: {
            reportId: string;
        };
    };
};

export type CreateDeviceReportWithKeyResponse = CreateDeviceReportWithKeyResponses[keyof CreateDeviceReportWithKeyResponses];

export type AuthenticationData = {
    body?: AuthenticationRequest;
    path?: never;
    query?: never;
    url: '/v1.0/authentication';
};

export type AuthenticationErrors = {
    400: ConnectivityError;
    401: ConnectivityError;
    403: ConnectivityError;
    404: ConnectivityError;
    500: ConnectivityError;
};

export type AuthenticationError = AuthenticationErrors[keyof AuthenticationErrors];

export type AuthenticationResponses = {
    200: ConnectivityBase & {
        object: {
            valid: boolean;
            type: string;
            role: string;
        };
    };
};

export type AuthenticationResponse = AuthenticationResponses[keyof AuthenticationResponses];

export type GetAssigneesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include deleted
         */
        includeDeleted?: boolean;
    };
    url: '/v1.0/assignee';
};

export type GetAssigneesErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetAssigneesError = GetAssigneesErrors[keyof GetAssigneesErrors];

export type GetAssigneesResponses = {
    /**
     * Assignees found
     */
    200: {
        assignee: Array<Assignee>;
    };
};

export type GetAssigneesResponse = GetAssigneesResponses[keyof GetAssigneesResponses];

export type CreateAssigneeData = {
    body?: AssigneeRequest;
    path?: never;
    query?: never;
    url: '/v1.0/assignee';
};

export type CreateAssigneeErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateAssigneeError = CreateAssigneeErrors[keyof CreateAssigneeErrors];

export type CreateAssigneeResponses = {
    /**
     * Assignee created
     */
    201: Assignee;
};

export type CreateAssigneeResponse = CreateAssigneeResponses[keyof CreateAssigneeResponses];

export type DeleteAssigneeData = {
    body?: never;
    path: {
        assigneeId: string;
    };
    query?: never;
    url: '/v1.0/assignee/{assigneeId}';
};

export type DeleteAssigneeErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type DeleteAssigneeError = DeleteAssigneeErrors[keyof DeleteAssigneeErrors];

export type DeleteAssigneeResponses = {
    /**
     * Assignee deleted
     */
    200: {
        assigneeId: string;
    };
};

export type DeleteAssigneeResponse = DeleteAssigneeResponses[keyof DeleteAssigneeResponses];

export type UpdateAssigneeLocationData = {
    body?: {
        locationId: string;
    };
    path: {
        assigneeId: string;
    };
    query?: never;
    url: '/v1.0/assignee/{assigneeId}/location';
};

export type UpdateAssigneeLocationErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateAssigneeLocationError = UpdateAssigneeLocationErrors[keyof UpdateAssigneeLocationErrors];

export type UpdateAssigneeLocationResponses = {
    /**
     * Assignee location updated
     */
    200: {
        assigneeId: string;
    };
};

export type UpdateAssigneeLocationResponse = UpdateAssigneeLocationResponses[keyof UpdateAssigneeLocationResponses];

export type UpdateAssigneePasswordData = {
    body?: {
        password: string;
    };
    path: {
        assigneeId: string;
    };
    query?: never;
    url: '/v1.0/assignee/{assigneeId}/password';
};

export type UpdateAssigneePasswordErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateAssigneePasswordError = UpdateAssigneePasswordErrors[keyof UpdateAssigneePasswordErrors];

export type UpdateAssigneePasswordResponses = {
    /**
     * Assignee password updated
     */
    200: {
        assigneeId: string;
    };
};

export type UpdateAssigneePasswordResponse = UpdateAssigneePasswordResponses[keyof UpdateAssigneePasswordResponses];

export type GetCommandsData = {
    body?: never;
    path: {
        deviceId: string;
    };
    query?: {
        /**
         * Command status
         */
        status?: Array<'pending' | 'pending-processing' | 'acknowledged'>;
    };
    url: '/v1.0/device/{deviceId}/command';
};

export type GetCommandsErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetCommandsError = GetCommandsErrors[keyof GetCommandsErrors];

export type GetCommandsResponses = {
    200: {
        command: Array<CommandWithStatus>;
    };
};

export type GetCommandsResponse = GetCommandsResponses[keyof GetCommandsResponses];

export type SendCommandData = {
    body?: BaseCommand;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/command';
};

export type SendCommandErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type SendCommandError = SendCommandErrors[keyof SendCommandErrors];

export type SendCommandResponses = {
    201: {
        commandId?: string;
    };
};

export type SendCommandResponse = SendCommandResponses[keyof SendCommandResponses];

export type ListDevicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include deleted
         */
        includeDeleted?: boolean;
    };
    url: '/v1.0/device';
};

export type ListDevicesErrors = {
    401: _Error;
    403: _Error;
    500: _Error;
};

export type ListDevicesError = ListDevicesErrors[keyof ListDevicesErrors];

export type ListDevicesResponses = {
    200: {
        devices: Array<Device>;
    };
};

export type ListDevicesResponse = ListDevicesResponses[keyof ListDevicesResponses];

export type CreateDeviceData = {
    body?: DeviceRequest;
    path?: never;
    query?: never;
    url: '/v1.0/device';
};

export type CreateDeviceErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    500: _Error;
};

export type CreateDeviceError = CreateDeviceErrors[keyof CreateDeviceErrors];

export type CreateDeviceResponses = {
    201: {
        deviceId?: string;
    };
};

export type CreateDeviceResponse = CreateDeviceResponses[keyof CreateDeviceResponses];

export type DeleteDeviceData = {
    body?: never;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}';
};

export type DeleteDeviceErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type DeleteDeviceError = DeleteDeviceErrors[keyof DeleteDeviceErrors];

export type DeleteDeviceResponses = {
    200: {
        deviceId: string;
    };
};

export type DeleteDeviceResponse = DeleteDeviceResponses[keyof DeleteDeviceResponses];

export type GetDeviceByIdData = {
    body?: never;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}';
};

export type GetDeviceByIdErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetDeviceByIdError = GetDeviceByIdErrors[keyof GetDeviceByIdErrors];

export type GetDeviceByIdResponses = {
    200: Device;
};

export type GetDeviceByIdResponse = GetDeviceByIdResponses[keyof GetDeviceByIdResponses];

export type UpdateDevicePasswordData = {
    body?: {
        password: string;
    };
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/password';
};

export type UpdateDevicePasswordErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateDevicePasswordError = UpdateDevicePasswordErrors[keyof UpdateDevicePasswordErrors];

export type UpdateDevicePasswordResponses = {
    200: {
        deviceId: string;
    };
};

export type UpdateDevicePasswordResponse = UpdateDevicePasswordResponses[keyof UpdateDevicePasswordResponses];

export type UpdateDeviceLocationData = {
    body?: {
        locationId: string;
    };
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/location';
};

export type UpdateDeviceLocationErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateDeviceLocationError = UpdateDeviceLocationErrors[keyof UpdateDeviceLocationErrors];

export type UpdateDeviceLocationResponses = {
    200: {
        deviceId: string;
    };
};

export type UpdateDeviceLocationResponse = UpdateDeviceLocationResponses[keyof UpdateDeviceLocationResponses];

export type ListDeviceEventsData = {
    body?: never;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/event';
};

export type ListDeviceEventsErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type ListDeviceEventsError = ListDeviceEventsErrors[keyof ListDeviceEventsErrors];

export type ListDeviceEventsResponses = {
    200: {
        event: Array<Event>;
    };
};

export type ListDeviceEventsResponse = ListDeviceEventsResponses[keyof ListDeviceEventsResponses];

export type UpdateDeviceMasterProgramData = {
    body?: BaseMasterProgram;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/masterprogram';
};

export type UpdateDeviceMasterProgramErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateDeviceMasterProgramError = UpdateDeviceMasterProgramErrors[keyof UpdateDeviceMasterProgramErrors];

export type UpdateDeviceMasterProgramResponses = {
    200: BaseMasterProgram;
};

export type UpdateDeviceMasterProgramResponse = UpdateDeviceMasterProgramResponses[keyof UpdateDeviceMasterProgramResponses];

export type GetPendingApprovalJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/approval/job';
};

export type GetPendingApprovalJobsErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetPendingApprovalJobsError = GetPendingApprovalJobsErrors[keyof GetPendingApprovalJobsErrors];

export type GetPendingApprovalJobsResponses = {
    /**
     * Jobs retrieved
     */
    200: {
        job?: Array<BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId>;
    };
};

export type GetPendingApprovalJobsResponse = GetPendingApprovalJobsResponses[keyof GetPendingApprovalJobsResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/job';
};

export type GetJobsErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetJobsError = GetJobsErrors[keyof GetJobsErrors];

export type GetJobsResponses = {
    /**
     * Jobs retrieved
     */
    200: {
        job?: Array<BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId>;
    };
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type GetJobByIdData = {
    body?: never;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/v1.0/job/{jobId}';
};

export type GetJobByIdErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetJobByIdError = GetJobByIdErrors[keyof GetJobByIdErrors];

export type GetJobByIdResponses = {
    /**
     * Job retrieved
     */
    200: BaseJobWithJobIdAndStatusAndAssigneeAndDeviceIdAndHistory;
};

export type GetJobByIdResponse = GetJobByIdResponses[keyof GetJobByIdResponses];

export type UpdateJobData = {
    body?: BaseJobWithAssigneeWithDeviceId;
    path: {
        jobId: string;
    };
    query?: never;
    url: '/v1.0/job/{jobId}';
};

export type UpdateJobErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateJobError = UpdateJobErrors[keyof UpdateJobErrors];

export type UpdateJobResponses = {
    /**
     * Job updated
     */
    200: BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type UpdateJobStatusData = {
    body?: JobUpdateStatus;
    path: {
        jobId: string;
    };
    query?: {
        /**
         * Force command
         */
        forceCommand?: boolean;
    };
    url: '/v1.0/job/{jobId}/status';
};

export type UpdateJobStatusErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateJobStatusError = UpdateJobStatusErrors[keyof UpdateJobStatusErrors];

export type UpdateJobStatusResponses = {
    /**
     * Job updated
     */
    200: JobUpdateStatus;
};

export type UpdateJobStatusResponse = UpdateJobStatusResponses[keyof UpdateJobStatusResponses];

export type ApproveJobData = {
    body?: {
        approval: boolean;
    };
    path: {
        jobId: string;
    };
    query?: never;
    url: '/v1.0/job/{jobId}/approval';
};

export type ApproveJobErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type ApproveJobError = ApproveJobErrors[keyof ApproveJobErrors];

export type ApproveJobResponses = {
    /**
     * Job approved
     */
    200: BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId;
};

export type ApproveJobResponse = ApproveJobResponses[keyof ApproveJobResponses];

export type GetDeviceJobsData = {
    body?: never;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/job';
};

export type GetDeviceJobsErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetDeviceJobsError = GetDeviceJobsErrors[keyof GetDeviceJobsErrors];

export type GetDeviceJobsResponses = {
    /**
     * Jobs retrieved
     */
    200: {
        job: Array<BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId>;
    };
};

export type GetDeviceJobsResponse = GetDeviceJobsResponses[keyof GetDeviceJobsResponses];

export type CreateJobData = {
    body?: BaseJobWithAssignee;
    path: {
        deviceId: string;
    };
    query?: never;
    url: '/v1.0/device/{deviceId}/job';
};

export type CreateJobErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Job created
     */
    201: BaseJobWithJobIdAndStatusAndAssigneeAndDeviceId;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type GetLocationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include deleted
         */
        includeDeleted?: boolean;
    };
    url: '/v1.0/location';
};

export type GetLocationsErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetLocationsError = GetLocationsErrors[keyof GetLocationsErrors];

export type GetLocationsResponses = {
    /**
     * Locations found
     */
    200: {
        location?: Array<Location>;
    };
};

export type GetLocationsResponse = GetLocationsResponses[keyof GetLocationsResponses];

export type CreateLocationData = {
    body?: BaseLocation;
    path?: never;
    query?: never;
    url: '/v1.0/location';
};

export type CreateLocationErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * Location created
     */
    201: Location;
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type DeleteLocationData = {
    body?: never;
    path: {
        locationId: string;
    };
    query?: never;
    url: '/v1.0/location/{locationId}';
};

export type DeleteLocationErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type DeleteLocationError = DeleteLocationErrors[keyof DeleteLocationErrors];

export type DeleteLocationResponses = {
    /**
     * Location deleted
     */
    200: {
        locationId: string;
    };
};

export type DeleteLocationResponse = DeleteLocationResponses[keyof DeleteLocationResponses];

export type GetMasterProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/masterprogram';
};

export type GetMasterProgramsErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetMasterProgramsError = GetMasterProgramsErrors[keyof GetMasterProgramsErrors];

export type GetMasterProgramsResponses = {
    /**
     * OK
     */
    200: {
        masterprogram: Array<BaseMasterProgramWithDetail>;
    };
};

export type GetMasterProgramsResponse = GetMasterProgramsResponses[keyof GetMasterProgramsResponses];

export type CreateTreatmentPlanData = {
    body?: TreatmentPlanCreateRequest;
    path: {
        group: string;
    };
    query?: never;
    url: '/v1.0/group/{group}/treatmentplan';
};

export type CreateTreatmentPlanErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateTreatmentPlanError = CreateTreatmentPlanErrors[keyof CreateTreatmentPlanErrors];

export type CreateTreatmentPlanResponses = {
    201: {
        treatmentplan?: Array<TreatmentPlanWithVersionAndName>;
    };
};

export type CreateTreatmentPlanResponse = CreateTreatmentPlanResponses[keyof CreateTreatmentPlanResponses];

export type GetTreatmentPlanData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1.0/treatmentplan';
};

export type GetTreatmentPlanErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetTreatmentPlanError = GetTreatmentPlanErrors[keyof GetTreatmentPlanErrors];

export type GetTreatmentPlanResponses = {
    200: {
        treatmentplan?: Array<TreatmentPlanWithVersionAndName>;
    };
};

export type GetTreatmentPlanResponse = GetTreatmentPlanResponses[keyof GetTreatmentPlanResponses];

export type GetTreatmentPlanByIdData = {
    body?: never;
    path: {
        treatmentPlanId: string;
    };
    query?: never;
    url: '/v1.0/treatmentplan/{treatmentPlanId}';
};

export type GetTreatmentPlanByIdErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetTreatmentPlanByIdError = GetTreatmentPlanByIdErrors[keyof GetTreatmentPlanByIdErrors];

export type GetTreatmentPlanByIdResponses = {
    200: TreatmentPlanWithVersionAndNameAndHistory;
};

export type GetTreatmentPlanByIdResponse = GetTreatmentPlanByIdResponses[keyof GetTreatmentPlanByIdResponses];

export type UpdateTreatmentPlanData = {
    body?: TreatmentPlanUpdate;
    path: {
        treatmentPlanId: string;
    };
    query?: never;
    url: '/v1.0/treatmentplan/{treatmentPlanId}';
};

export type UpdateTreatmentPlanErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateTreatmentPlanError = UpdateTreatmentPlanErrors[keyof UpdateTreatmentPlanErrors];

export type UpdateTreatmentPlanResponses = {
    200: TreatmentPlanWithVersionAndName;
};

export type UpdateTreatmentPlanResponse = UpdateTreatmentPlanResponses[keyof UpdateTreatmentPlanResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include deleted
         */
        includeDeleted?: boolean;
    };
    url: '/v1.0/user';
};

export type GetUsersErrors = {
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Users found
     */
    200: {
        user: Array<User>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body?: BaseUser;
    path?: never;
    query?: never;
    url: '/v1.0/user';
};

export type CreateUserErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * User created
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type UpdateUserLocationData = {
    body?: {
        locationId: string;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/v1.0/user/{userId}/location';
};

export type UpdateUserLocationErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type UpdateUserLocationError = UpdateUserLocationErrors[keyof UpdateUserLocationErrors];

export type UpdateUserLocationResponses = {
    /**
     * User location updated
     */
    200: {
        userId: string;
    };
};

export type UpdateUserLocationResponse = UpdateUserLocationResponses[keyof UpdateUserLocationResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/v1.0/user/{userId}';
};

export type DeleteUserErrors = {
    400: _Error;
    401: _Error;
    403: _Error;
    404: _Error;
    500: _Error;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * User deleted
     */
    200: {
        userId: string;
    };
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type ClientOptions = {
    baseURL: 'https://api-ext.acme-local.online:22233/controller' | 'http://localhost:22223/controller' | 'https://{environment}.acme-local.online/controller' | (string & {});
};